---
- name: Add static ip to nic on provisioning network
  become: true
  template:
    src: ifcfg-virthost-provision.j2
    dest: /etc/sysconfig/network-scripts/ifcfg-{{ virthost_provisioning_interface }}
    mode: 644
    owner: root
    group: root

- name: Ensure nic is up
  become: true
  command: ifup {{ virthost_provisioning_interface }}
