---
- name: Copy over provisioning nic script template
  template:
    src: add-provisioning-interface.sh.j2
    dest: "{{ working_dir }}/add-provisioning-interface.sh"
    mode: 0755

- name: wait for  script file to exist
  wait_for: path="{{ working_dir }}/add-provisioning-interface.sh"

- name: Add provisioning interface to the "brovc" bridge
  become: yes
  shell: >
    "{{ working_dir }}"/add-provisioning-interface.sh
  register: bridge_status
  ignore_errors: true

# if the above task fails it's possible the bridge has already
#  been added, this checks for that error message and fails
#  if it finds a different error
- name: Check if interface already added to "brovc" bridge
  command: /bin/false
  when: ("already a member" not in bridge_status.stderr) and ( bridge_status | failed )
