---
- name: Copy over provisioning nic script template
  template:
    src: add-provisioning-interface.sh.j2
    dest: {{ working_dir }}/add-provisioning-interface.sh
    mode: 0755

- name: Add provisioning interface to the "brovc" bridge
  shell: >
    "{{ working_dir }}/add-provisioning-interface.sh &> add-provisioning-interface.log"
