---
- include: baremetal-prep-virthost.yml
  when: undercloud_type == 'virt' and environment_type is defined

- include: deploy-stack.ml
  when: undercloud_type == 'ovb'

- name: Validate IPMI and instackenv.json
  hosts: undercloud
  gather_facts: yes
  roles:
    - validate-ipmi

- name:  Install the undercloud
  hosts: undercloud
  gather_facts: no
  roles:
    - tripleo/undercloud

- name:  copy over config files
  hosts: undercloud
  gather_facts: no
  roles:
    - overcloud-prep-config

- name:  Perpare the baremetal overcloud
  hosts: undercloud
  gather_facts: yes
  roles:
    - overcloud-prep-baremetal

- name:  Prepare the overcloud images for deployment
  hosts: undercloud
  gather_facts: no
  roles:
    - overcloud-prep-images

- name:  Prepare overcloud flavors
  hosts: undercloud
  gather_facts: no
  roles:
    - overcloud-prep-flavors

- name:  Prepare the undercloud networks for the overcloud deployment
  hosts: undercloud
  gather_facts: no
  roles:
    - overcloud-prep-network

- name:  Deploy the overcloud
  hosts: undercloud
  gather_facts: no
  roles:
    - tripleo-overcloud

# Add the overcloud nodes to the generated inventory.
- name:  Inventory the overcloud
  hosts: undercloud
  gather_facts: yes
  tags:
    - overcloud-deploy
  vars:
      inventory: all
  roles:
    - tripleo-inventory

- name:  Check the result of the deployment
  hosts: localhost
  tags:
    - overcloud-deploy
  tasks:
    - name: ensure the deployment result has been read into memory
      include_vars: "{{ local_working_dir }}/overcloud_deployment_result.json"

    # overcloud_deploy_result = ["failed", "passed"]
    - name: did the deployment pass or fail?
      debug: var=overcloud_deploy_result
      failed_when: overcloud_deploy_result == "failed"

# Validate the deployment
- name:  validate the overcloud
  hosts: undercloud
  tags:
    - overcloud-validate
  gather_facts: no
  roles:
    - { role: validate-simple, when: test_ping|bool }

# Execute tempest against the overcloud deployment
- name:  Execute tempest against the overcloud
  hosts: undercloud
  tags:
    - overcloud-validate
  gather_facts: no
  roles:
    - { role: validate-tempest, when: run_tempest|bool }

